name: Report a problem
description: Something did not work as expected
title: "[Issue]: "
labels: ["bug"]

body:
  - type: textarea
    id: message
    attributes:
      label: What happened?
      description: >
        Please describe what went wrong. <br><br>

        If helpful, you can include:<br>
        • What you were trying to do<br>
        • What you expected instead<br>
        • How we can see the same issue<br>
        • Screenshots (drag them into this field)
    validations:
      required: true
