name: Report a problem
description: Something did not work as expected
title: "[Issue]: "
labels: ["bug"]

body:
  - type: textarea
    id: message
    attributes:
      label: What happened?
      description: >
        Please describe what went wrong.

        If helpful, you can include:
        • What you were trying to do
        • What you expected instead
        • How we can see the same issue
        • Screenshots (drag them into this field)
    validations:
      required: true
