name: Suggest an improvement
description: Share an idea or feature you would like to see
title: "[Feature]: "
labels: ["enhancement"]

body:
  - type: textarea
    id: message
    attributes:
      label: What would you like to see?
      description: >
        Tell us your idea in a few sentences.<br><br>

        If helpful, you can include:<br>
        • What problem this would solve<br>
        • How you imagine it working<br>
        • Why it would be useful<br>
    validations:
      required: true
